### ISSUE TITLE
Segmentation fault with help command

### ISSUE THREAD

**Issue by llamafilm** [CESNET/UltraGrid#112]
I'm trying to check NDI sources.  I have installed NDI SDK version 4.5.3 and compiled UltraGrid from git master.  Is there anything else I can do to help troubleshoot this?

```
$ uv -t ndi:help --verbose=7
UltraGrid 1.6+ (tags/continuous rev 2c90fee5 built Dec  9 2020 16:45:10)

Display device   : none
Capture device   : ndi
Audio capture    : none
Audio playback   : none
MTU              : 1500 B
Video compression: none
Audio codec      : PCM
Network protocol : UltraGrid RTP
Audio FEC        : none
Video FEC        : none

[1607538459.176] Found empty UDP port pair 32768/32769
[1607538459.176] Connected IP version 6
    Last message repeated 1 times
[1607538459.176] Created database entry 0x625d4bf5 (1 sources)
Created new RTP session with SSRC 0x625d4bf5.
[1607538459.176] Added participant 625d4bf5
[1607538459.176] Socket recv buffer size set to 425984 B.
Display initialized-none
Usage:
	-t ndi[:help][:name=<n>][:url=<u>]
	where
		name
			name of the NDI source in form "MACHINE_NAME (NDI_SOURCE_NAME)"
		url
			URL, typically <ip> or <ip>:<port>

	available sources (tentative, format: name - url):


 0        0
 1        0
 2        0
 3        0
 4        0
 5        0
 6        0
 7        0
 8        0
 9        0

Lost:              0
Intervals:         0
Total:             0
ooo:               0 --    -nan

Segmentation fault
```

**Comment by llamafilm** [comment]
Actually the segmentation fault happens with all capture devices, including `uv -t testcard:help` and `uv -t none:help`

**Comment by MartinPulec** [comment]
Interesting, thanks - there could be something wrong that happens under some circumstances only - I cannot unfortunately reproduce that. Would you be able to generate a backtrace (eg with gdb - `gdb --args uv -t ndi:help --verbose=7`)? Not sure but hopefully it would be sufficient for me.

Thanks,
Martin

**Comment by llamafilm** [comment]
Sure, here it is
```
$ gdb --args uv -t testcard:help --verbose=7
GNU gdb (GDB) Red Hat Enterprise Linux 8.0.1-30.amzn2.0.3
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from uv...done.
(gdb) run
Starting program: /usr/local/bin/uv -t testcard:help --verbose=7
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff2b33700 (LWP 9230)]
[Thread 0x7ffff2b33700 (LWP 9230) exited]
[New Thread 0x7ffff2b33700 (LWP 9231)]
UltraGrid 1.6+ (tags/continuous rev 2c90fee5 built Dec  9 2020 16:45:10)

Display device   : none
Capture device   : testcard
Audio capture    : none
Audio playback   : none
MTU              : 1500 B
Video compression: none
Audio codec      : PCM
Network protocol : UltraGrid RTP
Audio FEC        : none
Video FEC        : none

[1607625061.294] Found empty UDP port pair 32768/32769
[1607625061.294] Connected IP version 6
    Last message repeated 1 times
[1607625061.294] Created database entry 0x491e1229 (1 sources)
Created new RTP session with SSRC 0x491e1229.
[1607625061.296] Added participant 491e1229
[1607625061.296] Socket recv buffer size set to 425984 B.
Display initialized-none
testcard options:
	-t testcard:<width>:<height>:<fps>:<codec>[:filename=<filename>][:p][:s=<X>x<Y>][:i|:sf][:still][:pattern=<pattern>]
where
	<filename> - use file named filename instead of default bars
	p - pan with frame
	s - split the frames into XxY separate tiles
	i|sf - send as interlaced or segmented frame (if none of those is set, progressive is assumed)
	still - send still image
	pattern - pattern to use, one of: bars, blank, gradient[=0x<AABBGGRR>], gradient2, noise, 0x<AABBGGRR>
	Supported codecs (testcard):
		8bits
			'I420' - planar YUV 4:2:0
			'RGBA' - Red Green Blue Alpha 32bit
			'RGB' - Red Green Blue 24bit
			'UYVY' - YUV 4:2:2
			'YUYV' - YUV 4:2:2
		10bits
			'R10k' - RGB 4:4:4
			'v210' - YUV 4:2:2
		12bits
			'RG48' - 16-bit RGB little-endian
			'R12L' - 12-bit packed RGB 4:4:4 little-endian

 0        0
 1        0
 2        0
 3        0
 4        0
 5        0
 6        0
 7        0
 8        0
 9        0
[Thread 0x7ffff2b33700 (LWP 9231) exited]

Lost:              0
Intervals:         0
Total:             0
ooo:               0 --    -nan


Thread 1 "uv" received signal SIGSEGV, Segmentation fault.
__pthread_join (threadid=0, thread_return=thread_return@entry=0x0)
    at pthread_join.c:45
45	  if (INVALID_NOT_TERMINATED_TD_P (pd))
(gdb) bt
#0  __pthread_join (threadid=0, thread_return=thread_return@entry=0x0)
    at pthread_join.c:45
#1  0x000000000057315b in stop_nat_traverse (s=s@entry=0x20dded0)
    at src/utils/nat.c:557
#2  0x00000000004a41cd in main (argc=<optimized out>, argv=<optimized out>)
    at src/main.cpp:1519
(gdb) quit

```

**Comment by MartinPulec** [comment]
I see, thanks a lot for debugging that - that was my fault in a recent code, I've just pushed a change (commit c8dde22c) that should fix that.

**Comment by llamafilm** [comment]
Thanks, this works.
